Add revert screen position worker
techisnothing/hkcinemaseat pull request #6
Opened 2017-05-20 05:33 UTC by ivan-ha

2017-05-22 09:20 UTC, samMeow requested changes

2017-05-22 09:20 UTC, samMeow commented on worker/random_score.js
> +    cinema_dirs.push(process.argv[i]);
why not simply
```js
cinema_dirs = process.argv.slice(3)
```

2017-05-22 09:20 UTC, samMeow commented on worker/revert_screen.js
> +    cinemas.push(process.argv[i]);
same

2017-05-22 09:20 UTC, samMeow commented on worker/random_score.js
> +    console.log('Usage: node random_score.js [brand] [cinemas]');
should have exit statement
```js
process.exit()
```

2017-05-22 09:22 UTC, ivan-ha commented on worker/random_score.js
> +    cinema_dirs.push(process.argv[i]);
fucking right😂
will change it tonight

2017-05-22 13:49 UTC, ivan-ha commented
done @samMeow

2017-05-23 02:43 UTC, samMeow approved these changes

2017-05-23 02:53 UTC, merged